import '../globals.css';

import Head from 'next/head';
import Layout from '@/components/Layout';
import SideNav from '@/components/SideNav';
import PrivateRoutes from '@/components/PrivateRoutes';

import { useState, useEffect } from 'react';
import ExploreAllPosts from '@/components/ExploreAllPosts';

const Explore = ({authenticatedUser}: any) => {    
    const [loading, setLoading] = useState<boolean>(true);
    const [sideNavActive, setSideNavActive] = useState<string>('');

    useEffect(() => {
        (async() => {
            setSideNavActive('Explore');
            setLoading(false);
        })();
    }, []); 

    return (
        <>
            <Head>
                <title>Instagram</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/instagram_icon.ico" />
            </Head>

            {
                !loading &&
                <Layout>
                    <SideNav authenticatedUser={authenticatedUser} sideNavActive={sideNavActive}/>
                    <ExploreAllPosts authenticatedUser={authenticatedUser} />
                </Layout>
            }
        </>
    )
}

export default PrivateRoutes(Explore);

export async function getServerSideProps(context: any) {
    const { res } = context;

    res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
    res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");

    return {
        props: {}
    };
}