import Head from "next/head";
import SideNav from "@/components/SideNav";
import Layout from "@/components/Layout";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import PrivateRoutes from "@/components/PrivateRoutes";
import AllSavedPosts from "@/components/AllSavedPosts";

const SavedAllPosts = ({authenticatedUser}: any) => {
    const router = useRouter();
    const { query } = router;
    
    const [loading ,setLoading] = useState<boolean>(true);
    const [isOwned, setIsOwned] = useState<boolean>(false);
    const [sideNavActive, setSideNavActive] = useState<string>('');
    

    useEffect(() => {
        (async() => {
            try {
                const response = await fetch(`${process.env.REACT_APP_API}/api/v1/instagram/profile/${query.profile}`, {
                    method: 'GET',
                    credentials: 'include'
                });

                const response2 = await fetch(`${process.env.REACT_APP_API}/api/v1/instagram/profile/${query.profile}/saved/all-posts`, {
                    method: 'GET',
                    credentials: 'include'
                });

                if (response.status !== 200) {
                    router.push('/home');
                } else {
                    const userProfile = await response.json();

                    if (userProfile.userProfile === undefined) {
                        router.push('/home');
                    }

                    if(userProfile.isOwned === false) {
                        router.push('/home');
                    }

                    setIsOwned(userProfile.isOwned);
                    setSideNavActive(userProfile.isOwned ? 'Profile' : '');
                    setLoading(false);
                }
            } catch (error) {
                router.push('/home');
            }
        })();
    }, []);

    return (
        <>
            <Head>
                <title>Instagram</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/instagram_icon.ico" />
            </Head>

            {
                !loading && 
                <Layout>
                    <SideNav authenticatedUser={authenticatedUser} sideNavActive={sideNavActive}/>
                    <div className="flex-1 pt-2">
                        <div className="mx-auto max-w-[955px] pt-4">
                            {
                                isOwned &&
                                <main className="w-full">
                                    <AllSavedPosts authenticatedUser={authenticatedUser}/>
                                </main>
                            }
                        </div>
                    </div>
                </Layout>
            }
            
        </>
    )
}

export default PrivateRoutes(SavedAllPosts);

export async function getServerSideProps(context: any) {
    const { res } = context;

    res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
    res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");

    return {
        props: {}
    };
}