import '../../../globals.css';

import Head from 'next/head';
import Layout from '@/components/Layout';
import SideNav from '@/components/SideNav';

import PrivateRoutes from '@/components/PrivateRoutes';
import { useEffect, useState } from 'react';
import ExploreHashTagPosts from '@/components/ExploreHashTagPosts';

const HashTag = ({authenticatedUser}: any) => {    
    const [sideNavActive, setSideNavActive] = useState<string>('');
    const [loading, setLoading] = useState<boolean>(true);

    useEffect(() => {
        (async() => {
            setSideNavActive('');
            setLoading(false);
        })();   
    }, []);

    return (
        <>
            <Head>
                <title>Instagram</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/instagram_icon.ico" />
            </Head>

            {
                !loading &&
                <>
                    <Layout>
                        <SideNav authenticatedUser={authenticatedUser} sideNavActive={sideNavActive}/>
                        <ExploreHashTagPosts authenticatedUser={authenticatedUser} />
                    </Layout>
                </>
            }
        </>
    )
}

export default PrivateRoutes(HashTag);

export async function getServerSideProps(context: any) {
    const { res } = context;

    res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
    res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");

    return {
        props: {}
    };
}